config/routes.rb
ActionController::Routing::Translator.prefix_on_default_locale = true

ActionController::Routing::Routes.draw do |map|
  map.resources :event_logs
  map.house_seasons 'house_seasons', :controller => "seasons", :action => 'house_seasons'
  map.resources :seasons
  map.resources :bookings
  map.resources :houses_bookings
  map.resources :bookings, :collection => { :sort => :post} 
  map.calculate "calculate", :controller => "bookings", :action=> "calculate"
  map.resources :taggables
  map.resources :tags
  map.resources :houses
  map.resources :pages
  map.resources :discounts
  map.resources :contact

  map.cart "cart", :controller => "houses", :action => "cart"
  map.special_offers "special_offers", :controller => "houses", :action => "index", :discount => true, :q => ''
  map.programs  "pages/programs", :controller => "pages", :action => "show", :page => "programs"
  map.infos_a_z "pages/infos_a_z", :controller => "pages", :action => "show", :page => "infos_a_z"
  map.map       "pages/map", :controller => "pages", :action => "show", :page => "map"
  map.weather   "pages/weather", :controller => "pages", :action => "show", :page => "weather"
  map.calendar  "pages/calendar", :controller => "pages", :action => "show", :page => "calendar"
  map.sights    "pages/sights", :controller => "pages", :action => "show", :page => "sights"
  map.offers    "pages/offers", :controller => "pages", :action => "show", :page => "offers"
  map.terms     "pages/terms", :controller => "pages", :action => "show", :page => "terms"
  map.impressum "pages/impressum", :controller => "pages", :action => "show", :page => "impressum"
  map.owners     "pages/owners", :controller => "pages", :action => "show", :page => "owners"
  map.login "login", :controller => "user_sessions", :action => "new"
  map.logout "logout", :controller => "user_sessions", :action => "destroy"

  map.setup "setup", :controller => "setup", :action => "index" 
  map.image "image", :controller => "image", :action => "index" 
  
  map.resources :user_sessions

  map.resources :users
  
  map.root :controller => "root", :action => "index"
  
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end
ActionController::Routing::Translator.translate_from_file('config','i18n-routes.yml')

app/models/house.rb
class House < ActiveRecord::Base
  translates :house_description

  has_one :discount, :dependent => :destroy
  has_many :houses_taggables
  has_many :taggables, :through => :houses_taggables, :order => :position
  has_many :houses_tags
  has_many :tags, :through => :houses_tags, :uniq => true
  has_many :houses_bookings
  has_many :bookings, :through => :houses_bookings, :uniq => true
  has_many :house_seasons
  has_many :seasons, :through => :house_seasons

  default_scope :order => 'code ASC', :include => [:tags, :discount]
  
  accepts_nested_attributes_for :discount, :allow_destroy => true
  accepts_nested_attributes_for :tags, :allow_destroy => true
  
  validates_presence_of :code, :city_id, :house_type_id, :condition_id, :furnishing_id
  validates_uniqueness_of :code
  
  named_scope :discounts, {:joins => :discount}
  named_scope :with_descriptions, {:joins => "JOIN house_translations ON houses.id=house_translations.house_id AND house_translations.locale='#{I18n.locale.to_s}'"}
  named_scope :scroll_pictures, lambda { |tag|
    {:joins => :houses_tags,
    :conditions => { :houses_tags => {:tag_id => tag }},
    }}

  def discounted?
    if self.discount.nil? or self.discount.new_record? or self.discount == 0
      false
    else
      true
    end
  end
  
  def pool?
    if self.pool.nil? or self.new_record? or self.pool == 0
      false
    else
      true
    end
  end
  
  def animals?
    if self.animals.nil? or self.new_record? or self.animals == 0
      false
    else
      true
    end
  end
  
  def city
    Tag.find(city_id).name
  end

  def house_type
    Tag.find(house_type_id).name
  end

  def condition
    Tag.find(condition_id).name
  end

  def furnishing
    Tag.find(furnishing_id).name
  end

  def terrace
    Tag.find(terrace_id).name unless terrace_id.nil?
  end

  def stove
    Tag.find(stove_id).name unless stove_id.nil?
  end

  def clima
    Tag.find(clima_id).name unless clima_id.nil?
  end

  def parking
    Tag.find(parking_id).name unless parking_id.nil?
  end

  def owner_place
    Tag.find(owner_place_id).name unless owner_place_id.nil?
  end

  def stripped_code
    self.code.sub(/-\d+$/,'')
  end

  def picture_urls(size)
    pictures.split(',').map{|id| id.sub(/-([0-9]+)$/,'_\1')}.map{|pid| APP_CONFIG['asset_server']+self.stripped_code+'/'+pid+"_#{size}.jpg" if pid !~ /\ |$^/ }.compact if pictures
  end

  def thumb
    id = pictures.split(',').select{|id| id =~ /[0-9\-_]+/}[0]
    APP_CONFIG['asset_server']+self.stripped_code+'/'+id+'_s.jpg' if id
  end
  
  def picture_ids
    pictures.split(',').select{|id| id =~ /[0-9\-_]+/}.map{|id| id.sub(/-([0-9]+)$/,'_\1')} if pictures
  end

  def picture_ids=(ids)
    self.pictures = ids.join(',')
  end
  
  def self.per_page
    10
  end

  def price(name)
    case name
    when /pre|post/
    self.price_pre_season_per_week || 0
    when /mid/
    self.price_mid_season_per_week || 0
    when /main/
    self.price_main_season_per_week || 0
    end
  end

  def daily_price(name)
    case name
    when /pre|post/
    self.price_pre_season_per_day || 0
    when /mid/
    self.price_mid_season_per_day || 0
    when /main/
    self.price_main_season_per_day || 0
    end
  end

  def formatted_price(name)
    case name
    when /pre|post/
    "%8.2f" % (self.price_pre_season_per_week || 0)
    when /mid/
    "%8.2f" % (self.price_mid_season_per_week || 0)
    when /main/
    "%8.2f" % (self.price_main_season_per_week || 0)
    end
  end

  def formatted_daily_price(name)
    case name
    when /pre|post/
    "%8.2f" % (self.price_pre_season_per_day || 0)
    when /mid/
    "%8.2f" % (self.price_mid_season_per_day || 0)
    when /main/
    "%8.2f" % (self.price_main_season_per_day || 0)
    end
  end

  def distance(item)
    self.method("distance_#{item}").call.to_i
  end

  def name
    "#{self.code} (#{self.house_type.strip}, #{self.city})"
  end

  def h_seasons
    if self.seasons.empty?
      Season.for_all.next_year.actives
    else
      self.seasons.next_year.actives
    end
  end
  
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_filter :root_authorize, :except => [:index, :show, :print, :cart, :empty_cart]
  before_filter :search_house, :except => [:index, :new, :create, :cart, :empty_cart]
  before_filter :get_cart, :only => [:index, :cart, :empty_cart, :print, :show]

  def index
    if request.xhr? and params[:autocomplete]
      search = House.searchlogic(params[:search])
      @houses = search.all
      unless @houses.is_a? Array
        respond_to do |format|
          format.js
        end
      else
        render :inline => "<%= auto_complete_result @houses, :code %>"
      end
    else
      tag = Taggable.find_by_field('category').tags.find_by_name(params[:category]) unless params[:category].blank?
      if tag
        search = tag.houses.with_descriptions.searchlogic
      else
        if params[:discount]
          search = House.discounts.with_descriptions.searchlogic
        else
          search = House.with_descriptions.searchlogic
        end
      end
      search.persons_gte = params[:q][:persons].to_i unless params[:q].nil? or params[:q][:persons].blank?
  #    search.persons_inda_house_gte = params[:q][:persons].to_i unless params[:q].nil? or params[:q][:persons].blank?
      search.code_like = params[:q][:code] unless params[:q].nil? or params[:q][:code].blank?
      unless params[:q].nil? or params[:q][:where].blank?
        city = Taggable.find_by_field('city_id').tags.find_by_name(params[:q][:where])
        search.city_id = city.id if city
      end
      if params[:advanced] and params[:q]
        house_type = Taggable.find_by_field('house_type_id').tags.find_by_name(params[:q][:type]) unless params[:q][:type].blank?
        search.house_type_id = house_type.id if house_type
        search.sat = params[:sat] unless params[:sat].blank? or params[:sat] != '1'
        search.clima_id = Taggable.find_by_field('clima_id').tags.select{|tag| tag.name(:locale => 'hu') != 'nincs' }.map{|tag| tag.id} unless params[:clima].blank? or params[:clima] != '1'
        search.internet = params[:internet] unless params[:internet].blank? or params[:internet] != '1'
        search.grill = params[:grill] unless params[:grill].blank? or params[:grill] != '1'
        search.pool = params[:pool] unless params[:pool].blank? or params[:pool] != '1'
        search.animals = params[:animals] unless params[:animals].blank? or params[:animals] != '1'
        parking = Taggable.find_by_field('parking_id').tags.find_by_name(params[:q][:parking]) unless params[:q][:parking].blank?
        search.parking_id = parking.id if parking
        search.distance_center_lte = params[:q][:distance_center].to_i unless params[:q][:distance_center].blank?
        search.distance_beach_lte = params[:q][:distance_beach].to_i unless params[:q][:distance_beach].blank?
      end
      if request.format.to_s =~ /xml/
        order = 'updated_at DESC'
      end
      @houses, @houses_count = search.all(:select => "houses.id,code, city_id, persons, children, animals, pictures, house_type_id, condition_id, furnishing_id, floor_area, distance_center, distance_beach, distance_restaurant, distance_shop, distance_mainroad, distance_station, houses.updated_at", :order => order).paginate(:page => params[:page], :per_page => 10), search.count
      @feed_url = request.url.sub(/houses/,'houses.xml')
      respond_to do |format|
        format.html # index.html.erb
        format.xml #  { render :xml => @houses }
      end
    end
  end

  def show
  end

  def print
    render "show", :layout => 'print'
  end

  def new
    @house = House.new
    @discount = @house.build_discount
    @house.taggables.build
    @house.tags.build
    @empties = empties_helper
  end
  
  def create
    @house = House.new(params[:house])
    @empties = empties_helper
    if @house.save
      flash[:notice] = t "admin.house_added", :house => @house.code
      redirect_to @house
    else
      render :action => 'new'
    end
  end
  
  def edit
    @house.taggables.build
    @house.tags.build
    if @house.discounted?
      @discount = @house.discount
    else
      @discount = @house.build_discount
    end
  end
  
  def update
    if @house.update_attributes(params[:house])
      @house.discount.destroy unless params[:discounted]
      flash[:notice] = t "admin.house_updated", :house => @house.code
      redirect_to @house
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @house.destroy
    flash[:notice] = t "admin.house_deleted", :house => @house.code
    redirect_to houses_url
  end
  
  def cart
    begin
      house = House.find(params[:id]) if params[:id]
    rescue ActiveRecord::RecordNotFound
      logger.error("Attempt to access invalid house #{params[:id]}")
      redirect_to_index("invalid_house")
    else
      if params[:cart] == 'add'
    if @cart.limit_exceed?
      flash[:error] = t :cart_limit
    else
      @cart.add_house(house)
      flash[:notice] = t "house_added_to_cart", :house => house.code
    end
      end
      if params[:cart] == 'del'
	@cart.remove_house(house)
	flash[:notice] = t "house_removed_from_cart", :house => house.code
      end
      @selected = House.find_all_by_id(@cart.items)
      if params[:cart]
	redirect_to :back, :anchor => "house_#{params[:id]}"
      end
    end
  end

  def empty_cart
    session[:cart] = nil
    redirect_to_index("cart_is_empty")
  end

  private

  def search_house
    @house = House.find(params[:id])
  end

  def get_cart
    @cart = find_cart
  end

  def redirect_to_index(msg)
    flash[:notice] = t(msg)
    redirect_to :action => :index
  end

  def expire_caches
    expire_action :controller => :root, :action => :index
    expire_fragment :controller => :root, :action => :index
  end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_cart.html.erb
<div class="span-18 last cart">
  <%= render :partial => '/houses/cart_item', :locals => {:cart_item => selected} %>
</div>

<div><%= button_to t("Go to Cart"), :controller => :houses, :action => :cart %></div>

app/views/houses/_cart_item.html.erb
<% link_to cart_item do %>
  <%= image_tag cart_item.picture_ids[0] if cart_item.picture_ids %>
<% end  if cart_item %>
  <div class="item details">
<%= truncate( cart_item.house_description(80), :length => 40 ) if cart_item %>
  </div>

app/views/houses/_details.html.erb
<div id="house_<%= house.id %>" class="mini">
  <div class="span-18 last">
    <div class="span-16">
    <span class="label"><%= t :city %>:</span>
    <span class="field"><%=h house.city %></span>
&nbsp;
    <span class="label"><%= t :code %>:</span>
    <span class="field"><%=h house.code %></span>
    </div>
    <div class="span-2 last">
    <%= check_box_tag "checked_#{house.id}", 1 %>
    </div>
<br /><% if house.discounted?  %>
    <span class="label"><%= t :discount %>:</span>
    <span class="field"><%=h house.discount.description %></span>
    <% end %>
  </div>
  <div class="span-6">
    <span class="field" rowspan="10"><%= image_tag house.picture_ids[0], :size => '210x140' %></span>
  </div>
  <div class="span-6">
    <span class="label"><%= t :persons %>:</span>
    <span class="field"><%=h house.persons %> <%= t('pers') %></span>
  <br />
    <span class="label"><%= t :house_type_id %>:</span>
    <span class="field"><%=h house.house_type %></span>
  <br />
    <span class="label"><%= t :condition_id %>:</span>
    <span class="field"><%=h house.condition %></span>
  <br />
    <span class="label"><%= t :furnishing_id %>:</span>
    <span class="field"><%=h house.furnishing %></span>
  <br />
    <span class="label"><%= t :floor_area %>:</span>
    <span class="field"><%=h house.floor_area %> <%= t('sqmeter') %></span>
  </div>
  <div class="span-6 last">
    <span class="label"><%= t :animals %>:</span>
    <span class="field"><%= house.animals==1 ? t('yes_animal') : t('no_animal') %></span>
  <br />
    <span class="label"><%= t :distance_center %>:</span>
    <span class="field"><%=h house.distance_center %> <%= t('meter') %></span>
  <br />
    <span class="label"><%= t :distance_beach %>:</span>
    <span class="field"><%=h house.distance_beach %> <%= t('meter') %></span>
  <br />
    <span class="label"><%= t :distance_shop %>:</span>
    <span class="field"><%=h house.distance_shop %> <%= t('meter') %></span>
  <br />
    <span class="label"><%= t :distance_restaurant %>:</span>
    <span class="field"><%=h house.distance_restaurant %> <%= t('meter') %></span>
  </div>
  <div class="span-18 last">
    <div class="span-3">
    <span class="field"><%= link_to t("Details"), house %></span>
    </div>
    <div class="span-3">
    <span class="field"><%= link_to t("Photos"), house %></span>
    </div>
    <div class="span-3">
    <span class="field"><%= link_to t("Booking"), house %></span>
    </div>
    <div class="span-3">
    <span class="field"><%= link_to_function t("Select"), 
"if ($('checked_#{house.id}').checked) { $('checked_#{house.id}').checked=false } else { $('checked_#{house.id}').checked=true }" %></span>
    </div>
    <div class="span-3 last">
    <span class="field"><%= link_to t("Print"), house %></span>
    </div>
<% if root_admin? %>
  <br />
    <span class="field"><%= link_to t("Edit"), edit_house_path(house) %></span>
    <span class="field"><%= link_to t("Destroy"), house, :confirm => t('Are you sure?'), :method => :delete %></span>
<% end %>
  </div>
</div>

app/views/houses/_discount_form.html.erb
<div id="discount">
  <%= form.label t('admin.discount_description') %><br />
  <%= form.text_area :description, :rows => 5 %>
</div>

app/views/houses/_form.html.erb
<% form_for @house do |f| %>
  <%= f.error_messages %>
  <a name="details"></a>
  <% field_set_tag t('admin.house_basics') do %>
    <p>
      <%= f.label t('admin.city_id') %><br />
      <%= f.collection_select :city_id, Taggable.find_by_field('city_id').tags, :id, :name %>
    </p>
    <p>
      <%= f.label t('admin.code') %><br />
      <%= f.text_field :code %>
    </p>
    <p>
      <%= f.label t('admin.persons') %><br />
      <%= f.text_field :persons %>
    </p>
    <p>
      <%= f.label t('admin.children') %><br />
      <%= f.text_field :children %>
    </p>
    <p>
      <%= f.label t('admin.floor_area') %><br />
      <%= f.text_field :floor_area %>
    </p>
    <p>
      <%= f.label t('admin.house_type_id') %><br />
      <%= f.collection_select :house_type_id, Taggable.find_by_field('house_type_id').tags, :id, :name, :prompt => t(:select_house_type) %>
    </p>
    <p>
      <%= f.label t('admin.condition_id') %><br />
      <%= f.collection_select :condition_id, Taggable.find_by_field('condition_id').tags, :id, :name, :prompt => t(:select_condition) %>
    </p>
    <p>
      <%= f.label t('admin.furnishing_id') %><br />
      <%= f.collection_select :furnishing_id, Taggable.find_by_field('furnishing_id').tags, :id, :name, :prompt => t(:select_furnishing) %>
    </p>
    <div>
    <% field = Taggable.find_by_position(6) %>
    <p>
      <%= f.label field.name %><br />
	<% for tag in field.tags %>
	  <%= check_box_tag 'house[tag_ids][]', tag.id, @house.tags.include?(tag) %>
	  <%= f.label tag.name %><br />
	<% end %>
    </p>
    <% field = Taggable.find_by_position(80) %>
    <p>
      <%= f.label field.name %><br />
	<% for tag in field.tags %>
	  <%= check_box_tag 'house[tag_ids][]', tag.id, @house.tags.include?(tag) %>
	  <%= f.label tag.name %><br />
	<% end %>
    </p>
    <% field = Taggable.find_by_position(-1) %>
    <p>
      <%= f.label field.name %><br />
  <% for tag in field.tags %>
    <%= check_box_tag 'house[tag_ids][]', tag.id, @house.tags.include?(tag) %>
    <%= f.label tag.name %><br />
  <% end %>
    </p>
  </div>
  <% end %>
  <% field_set_tag t('house_layout') do %>
    <% for field in Taggable.find_all_by_position([8, 9, 10, 11]) %>
    <p>
      <%= f.label field.name %><br />
	<% for tag in field.tags %>
	  <%= check_box_tag 'house[tag_ids][]', tag.id, @house.tags.include?(tag) %>
	  <%= f.label tag.name %><br />
	<% end %>
    </p>
    <% end %>
  <% end %>
  <% field_set_tag t('house_rooms') do %>
    <% for field in %w(living_dining_room bedroom living_room living_dining_kitchen kitchen dining_room kitchen_dining_room) %>
    <p>
      <%= f.label t("admin.#{field}") %><br />
      <%= f.text_field field %>
    </p>
    <% end %>
    <p>
      <%= f.label t('admin.terrace_id') %><br />
      <%= f.collection_select :terrace_id, Taggable.find_by_field('terrace_id').tags, :id, :name, :prompt => t(:select_terrace) %>
    </p>
    <p>
      <%= f.label t('admin.balcony_id') %><br />
      <%= f.collection_select :balcony_id, Taggable.find_by_field('balcony_id').tags, :id, :name, :prompt => t(:select_balcony) %>
    </p>
    <p>
      <%= f.check_box :garden %>
      <%= f.label t('admin.garden') %><br />
    </p>
  <% end %>
  <% field_set_tag t('house_rooms_sq') do %>
    <% for field in %w(living_room_sq living_dining_room_sq living_dining_kitchen_sq kitchen_sq dining_room_sq kitchen_dining_room_sq terrace_sq balcony_sq yard_sq) %>
    <p>
      <%= f.label t("admin.#{field}") %><br />
      <%= f.text_field field %>
    </p>
    <% end %>
  <% end %>
  <% field_set_tag t('house_beds') do %>
    <% for field in %w(double_bed single_bed extra_bed pull_out_bed) %>
    <p>
      <%= f.label t("admin.#{field}") %><br />
      <%= f.text_field field %>
    </p>
    <% end %>
  <% end %>
  <% field_set_tag t('house_bathrooms') do %>
    <p>
      <%= f.label t('admin.bathrooms') %><br />
      <%= f.text_field :bathrooms %>
    </p>
    <% for field in %w(shower bathtub) %>
    <p>
      <%= f.check_box field %>
      <%= f.label t("admin.#{field}") %><br />
    </p>
    <% end %>
  <% end %>
  <% field_set_tag t('house_wc') do %>
    <p>
      <%= f.label t('admin.wcs') %><br />
      <%= f.text_field :wcs %>
    </p>
    <p>
      <%= f.check_box :wc_separated %>
      <%= f.label t('admin.wc_separated') %><br />
    </p>
  <% end %>
  <% field_set_tag t('house_kitchen') do %>
    <% for field in %w(fridge coffee_machine micro) %>
    <p>
      <%= f.label t("admin.#{field}") %><br />
      <%= f.text_field field %>
    </p>
    <% end %>
    <p>
      <%= f.label t('admin.stove_id') %><br />
      <%= f.collection_select :stove_id, Taggable.find_by_field('stove_id').tags, :id, :name, :prompt => t(:select_stove) %>
    </p>
  <% end %>
  <% field_set_tag t('house_inters') do %>
    <p>
      <%= f.label t("admin.sat") %><br />
      <%= f.text_field :sat %>
    </p>
    <p>
      <%= f.check_box :internet %>
      <%= f.label t("admin.internet") %><br />
    </p>
    <p>
      <%= f.label t('admin.clima_id') %><br />
      <%= f.collection_select :clima_id, Taggable.find_by_field('clima_id').tags, :id, :name, :prompt => t(:select_clima) %>
    </p>
  <% end %>
  <% field_set_tag t('house_outers') do %>
    <p>
      <%= f.check_box :pool, :onchange => "$('pool_sq').toggle()" %>
      <%= f.label t('admin.pool') %><br />
    </p>
    <div id="pool_sq"<%= "style='display:none'" unless @house.pool? %>>
      <p>
	<%= f.label t('admin.pool_sq') %><br />
	<%= f.text_field :pool_sq %>
      </p>
    </div>
    <% for field in %w(garden_seats grill sunbath_seat playground) %>
    <p>
      <% if field != 'sunbath_seat' %>
      <%= f.check_box field %>
      <%= f.label t("admin.#{field}") %><br />
      <% else %>
      <%= f.label t("admin.#{field}") %><br />
      <%= f.text_field field %>    
      <% end %>
    </p>
    <% end %>
    <p>
      <%= f.label t('admin.parking_id') %><br />
      <%= f.collection_select :parking_id, Taggable.find_by_field('parking_id').tags, :id, :name, :prompt => t(:select_parking) %>
    </p>
  <% end %>
  <% field_set_tag t('house_distances') do %>
    <p>
      <%= f.label t('admin.distance_center') %><br />
      <%= f.text_field :distance_center %>
    </p>
    <p>
      <%= f.label t('admin.distance_beach') %><br />
      <%= f.text_field :distance_beach %>
    </p>
    <p>
      <%= f.label t('admin.distance_aquapark') %><br />
      <%= f.text_field :distance_aquapark %>
    </p>
    <p>
      <%= f.label t('admin.distance_shop') %><br />
      <%= f.text_field :distance_shop %>
    </p>
    <p>
      <%= f.label t('admin.distance_station') %><br />
      <%= f.text_field :distance_station %>
    </p>
    <p>
      <%= f.label t('admin.distance_medical') %><br />
      <%= f.text_field :distance_medical %>
    </p>
    <p>
      <%= f.label t('admin.distance_mainroad') %><br />
      <%= f.text_field :distance_mainroad %>
    </p>
    <p>
      <%= f.label t('admin.distance_restaurant') %><br />
      <%= f.text_field :distance_restaurant %>
    </p>
  <% end %>
  <% field_set_tag t('admin.house_owner_infos') do %>
    <% field = Taggable.find_by_position(61) %>
    <p>
      <%= f.label field.name %><br />
	<% for tag in field.tags %>
	  <%= check_box_tag 'house[tag_ids][]', tag.id, @house.tags.include?(tag) %>
	  <%= f.label tag.name %><br />
	<% end %>
    </p>
    <p>
      <%= f.label t('admin.owner_place_id') %><br />
      <%= f.collection_select :owner_place_id, Taggable.find_by_field('owner_place_id').tags, :id, :name, :prompt => t(:select_owner_place) %>
    </p>
  <% end %>
  <% field_set_tag t('admin.house_animals') do %>
    <p>
      <%= f.check_box :animals, :onchange => "$('animal_charge').toggle()" %>
      <%= f.label t('admin.animals') %>
    </p>
    <div id="animal_charge"<%= "style='display:none'" unless @house.animals? %>>
      <p>
  <%= f.check_box :animal_charge %>
	<%= f.label t('admin.animal_charge') %>
      </p>
    </div>
  <% end %>
  <% field_set_tag t('admin.house_price_day') do %>
    <p>
      <%= f.label t('admin.price_pre_season') %><br />
      <%= f.text_field :price_pre_season_per_day %>
    </p>
    <p>
      <%= f.label t('admin.price_mid_season') %><br />
      <%= f.text_field :price_mid_season_per_day %>
    </p>
    <p>
      <%= f.label t('admin.price_main_season') %><br />
      <%= f.text_field :price_main_season_per_day %>
    </p>
  <% end %>
  <% field_set_tag t('admin.house_price_week') do %>
    <p>
      <%= f.label t('admin.price_pre_season') %><br />
      <%= f.text_field :price_pre_season_per_week %>
    </p>
    <p>
      <%= f.label t('admin.price_mid_season') %><br />
      <%= f.text_field :price_mid_season_per_week %>
    </p>
    <p>
      <%= f.label t('admin.price_main_season') %><br />
      <%= f.text_field :price_main_season_per_week %>
    </p>
  <% end %>
  <% field_set_tag t('admin.house_description') do %>
    <div>
      <%= check_box_tag :discounted, 1, @house.discounted?, :onchange => "$('discount_description').toggle()" %>
      <%= f.label t('admin.discounted') %> <br />
    </div>
    <div id="discount_description"<%= "style='display:none'" unless @house.discounted? %>>
    <% f.fields_for :discount do |d| -%>
    <%= render :partial => 'discount_form', :locals => { :form => d } %>
    <% end %>
    </div>
    <div>
      <%= f.label t('admin.description') %><br />
      <%= f.text_area :house_description, :rows => 5  %>
    </div>
    <div>
      <%= f.label t('admin.admin_description') %><br />
      <%= f.text_area :admin_description, :rows => 5  %>
    </div>
  <% end %>
<a name="photos"></a>
  <% field_set_tag t('house_photos') do %>
  <ul id="sortable">
    <%
      last = (@house.picture_ids && @house.picture_ids.size > 8 ? @house.picture_ids.size : 8)
      (0..last).each do |id| %>
      <% content_tag :li, id do %>
      <span class="handle">[mozgat]
      <%= image_tag @house.picture_urls('s')[id] if id and @house.picture_ids and @house.picture_ids[id] and @house.picture_urls('s') and @house.picture_urls('s')[id] %>
      </span>
      <%= f.label t('admin.picture_url', :position => id+1) %>
      <%= text_field_tag 'house[picture_ids][]', @house.picture_ids ? @house.picture_ids[id] : '' %>
      <% end %>
    <% end %>
    </ul>
    <%= sortable_element("sortable", :handle => "handle") %>
  <% end %>
  <p><%= f.submit t(:submit) %></p>
<% end %>